INSERT INTO PRODUCT (ID, CODE, NAME, PRICE) VALUES (1, 'VOUCHER', 'Cabify Voucher', 5.00);
INSERT INTO PRODUCT (ID, CODE, NAME, PRICE) VALUES (2, 'TSHIRT', 'Cabify T-Shirt', 20.00);
INSERT INTO PRODUCT (ID, CODE, NAME, PRICE) VALUES (3, 'MUG', 'Cabify Coffee Mug', 7.50);