INSERT INTO PRODUCT (ID, CODE, NAME, PRICE) VALUES (1, 'PROMOTION_FREE_PRODUCT_CODE', 'Cabify Voucher', 5.00);
INSERT INTO PRODUCT (ID, CODE, NAME, PRICE) VALUES (2, 'PROMOTION_DISCOUNT_PRODUCT_CODE', 'Cabify T-Shirt', 20.00);
INSERT INTO PRODUCT (ID, CODE, NAME, PRICE) VALUES (3, 'MUG', 'Cabify Coffee Mug', 7.50);