INSERT INTO PRODUCT (ID, CODE, NAME, PRICE) VALUES (1, 'VOUCHER', 'Voucher', 5.00);
INSERT INTO PRODUCT (ID, CODE, NAME, PRICE) VALUES (2, 'TSHIRT', 'T-Shirt', 20.00);
INSERT INTO PRODUCT (ID, CODE, NAME, PRICE) VALUES (3, 'MUG', 'Coffee Mug', 7.50);